### ISSUE TITLE
GeneralShardedCounter and memcache mismatch

### ISSUE THREAD

**Issue by twall** [GoogleCloudPlatform/appengine-sharded-counters-python#4]
If a GeneralShardedCounter is accessed often enough, the memcache representation will get out of sync.

Running 100-1000 parallel operations incrementing the counter (and occasionally reading its value) results in memcache reaching a level between 0.1% and 1% higher than the actual sharded counter value.  I've tested this numerous times on 10,000 operations; the counter reaches 10,000 as the operations (task queue tasks) are spawned, but the count of operations finished (each operation increments the counter on exit) reaches anywhere from 10,001 to 10,100 or thereabout.

If the memcache value expires, and any number of operations has just incremented a shard but not yet incremented memcache, a call to `get_count` will count the just-incremented shards, store the value in memcache, and _then_ memcache will be incremented, leaving those operations counted twice, with a resulting higher count in memcache.

My workaround is to invalidate the cache if I want to get a more "accurate" number, but I think the memcache results here should be taken as no more than a hint.

**Comment by ashish1294** [comment]
Memcache is incremented inside a datastore transaction. And Memcache doesn't support transactions. So updates made to memcache inside transactions may be applied to it multiple times.

So the over-counting is an expected behaviour I guess.

**Comment by webmaven** [comment]
Can this issue be closed?

**Comment by theacodes** [comment]
No, this is definitely an issue and a drawback of this design. I'm not quite sure how to address this yet.

**Comment by webmaven** [comment]
@jonparrott, any ideas yet?

**Comment by theacodes** [comment]
> So the over-counting is an expected behaviour I guess.

That's basically the answer. Memcache can give you an approximate count, but you'll need to do a read in a transaction to get an absolutely count at a point in time.

Usually sharded counters are incrementing so quickly an approximate count (or a slightly stale count) is all you should depend on unless you plan on snapshotting for doing time series analysis.
